!function(t,e){"use strict";function n(){if(!a){a=!0;for(var t=0;t<i.length;t++)i[t].fn.call(window,i[t].ctx);i=[]}}function o(){"complete"===document.readyState&&n()}t=t||"docReady",e=e||window;var i=[],a=!1,r=!1;e[t]=function(t,e){return a?void setTimeout(function(){t(e)},1):(i.push({fn:t,ctx:e}),void("complete"===document.readyState?setTimeout(n,1):r||(document.addEventListener?(document.addEventListener("DOMContentLoaded",n,!1),window.addEventListener("load",n,!1)):(document.attachEvent("onreadystatechange",o),window.attachEvent("onload",n)),r=!0)))}}("docReady",window),function(){"use strict";for(var t=0,e=["ms","moz","webkit","o"],n=0;n<e.length&&!window.requestAnimationFrame;++n)window.requestAnimationFrame=window[e[n]+"RequestAnimationFrame"],window.cancelAnimationFrame=window[e[n]+"CancelAnimationFrame"]||window[e[n]+"CancelRequestAnimationFrame"];window.requestAnimationFrame||(window.requestAnimationFrame=function(e){var n=(new Date).getTime(),o=Math.max(0,16-(n-t)),i=window.setTimeout(function(){e(n+o)},o);return t=n+o,i}),window.cancelAnimationFrame||(window.cancelAnimationFrame=function(t){clearTimeout(t)})}(),function(t,e){"use strict";function n(){var t=c();t>=80?m.classList.add("fixed"):m.classList.remove("fixed")}function o(t){if("undefined"!=typeof t&&null!==t){var e=t.value.toString();if(e.length>1&&-1!==e.indexOf("#"))return!0}return!1}function i(t){return.5*(1-Math.cos(Math.PI*t))}function a(n,o){var a,s=c(),u=r(n),d=Date.now();u=0>u?0:u;var m=function(){var n=Date.now(),r=(n-d)/o;r=r>1?1:r;var c=i(r),f=s+(u-s)*c;return t.scrollTo(0,f),f===u?void(s=u=e):void(a=t.requestAnimationFrame(m))};a&&t.cancelAnimationFrame(a),a=t.requestAnimationFrame(m)}function r(t){for(var e=-1*s;"undefined"!=typeof t.offsetParent&&null!==t.offsetParent;)e+=t.offsetTop+(null!==t.clientTop?t.clientTop:0),t=t.offsetParent;return e}function c(){return t.pageYOffset!==e?t.pageYOffset:document.documentElement.scrollTop!==e?document.documentElement.scrollTop:document.body.scrollTop}var s=50,u=1e3,d=document.getElementsByTagName("a");Array.prototype.forEach.call(d,function(n){var i=n.attributes.href;o(i)&&n.addEventListener("click",function(n){n.preventDefault();var o=this.attributes.href.value.toString(),i=o.substr(0,o.indexOf("#")),r=o.substr(o.indexOf("#")+1),c=document.getElementById(r);"undefined"!=typeof c&&null!==c&&(t.history&&"function"==typeof t.history.pushState&&t.history.pushState({},e,i+"#"+r),a(c,u))})});var m=document.getElementById("bar");t.addEventListener("scroll",function(){t.requestAnimationFrame(n)},!1)}(window),/*!
 *
 *  Web Starter Kit
 *  Copyright 2014 Google Inc. All rights reserved.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License
 *
 */
function(){"use strict";function t(){i.classList.remove("open"),a.classList.remove("open"),o.classList.remove("open")}function e(){i.classList.toggle("open"),a.classList.toggle("open"),o.classList.toggle("open"),o.classList.add("opened")}var n=document.querySelector.bind(document),o=n(".navdrawer-container"),i=document.body,a=n(".app-bar"),r=n(".menu"),c=n("main");c.addEventListener("click",t),r.addEventListener("click",e),o.addEventListener("click",function(e){("A"===e.target.nodeName||"LI"===e.target.nodeName)&&t()}),"function"!=typeof String.prototype.startsWith&&(String.prototype.startsWith=function(t){return this.slice(0,t.length)===t}),"function"!=typeof String.prototype.endsWith&&(String.prototype.endsWith=function(t){return this.slice(-t.length)===t})}();